version: '3'
services:

  service_a:
    image: grpc-svc:v1
    hostname: servicea
    container_name: servicea
    environment:
      - GRPC_SERVER_PORT=5051
      - GRPC_CLIENT_HOST=serviceb
      - GRPC_CLIENT_PORT=5051
      - JSON_CLIENT_HOST=serviceb
      - JSON_SERVER_PORT=8080
      - JSON_CLIENT_PORT=8080
    ports:
      - "8081:8080"
    expose:
      - "8080"
      - "5051"
    networks:
      - mesh

  service_b:
    image: grpc-svc:v1
    hostname: serviceb
    container_name: serviceb
    environment:
      - GRPC_SERVER_PORT=5051
      - GRPC_CLIENT_HOST=servicea
      - GRPC_CLIENT_PORT=5051
      - JSON_CLIENT_HOST=servicea
      - JSON_SERVER_PORT=8080
      - JSON_CLIENT_PORT=8080
    ports:
      - "8082:8080"
    expose:
      - "8080"
      - "5051"
    networks:
      - mesh

networks:
  mesh: